<?php

namespace Calculation;

Class Readme extends \Ecc
{

    /**
     * @var $f3 \Base
     * @var $blc \Blc
     * @var $ec \Ec\Ec
     * @throws \Exception
     */
    public function calc($f3, $blc, $ec)
    {
        $f3->set('HIGHLIGHT', true);

        $blc->region0('toc', 'Tartalomjegyzék');
            $blc->toc();
        $blc->region1('toc');

        $text1 = file_get_contents($f3->BASE.'vendor/resist/ecc-calculations/README.md');
        $blc->md($text1);

        $blc->hr();
        $blc->h1('Annex', 'Autogenerated tests, lists and snippets');

        $blc->h2('Snippets');

        $blc->h3('JSXGraph charts');
        $blc->jsxDriver();
        $js = '
        var board = JXG.JSXGraph.initBoard("test", {boundingbox: [-5,40,5,-5], axis:true, showCopyright:false, keepaspectratio: false, showNavigation: true});
        var p = board.create("point",[1,5], {name:"1", face:"o", color:"green"});
        var p = board.create("point",[2,20], {name:"2", face:"o", color:"green"});
        var p = board.create("point",[3,35], {name:"?", face:"o", color:"red"});
        ';
        $blc->jsx('test', $js);
        $blc->pre('
$blc->jsxDriver();
$js = \'
var board = JXG.JSXGraph.initBoard("test", {boundingbox: [-5,40,5,-5], axis:true, showCopyright:false, keepaspectratio: false, showNavigation: true});
var p = board.create("point",[1,5], {name:"1", face:"o", color:"green"});
var p = board.create("point",[2,20], {name:"2", face:"o", color:"green"});
var p = board.create("point",[3,35], {name:"?", face:"o", color:"red"});
\';
$blc->jsx(\'test\', $js);
        ');

        $blc->h3('Google Charts based Lavacharts');
        $lava = new \Khill\Lavacharts\Lavacharts;
        $dataTableSlope = $lava->DataTable();

        $blc->pre('
// Initialize Lavacharts driver:
$lava = new \Khill\Lavacharts\Lavacharts;        
        ');

        $dataTableSlope->addNumberColumn('x')
            ->addNumberColumn('y')
            ->addRow([0, 0])
            ->addRow([100, 3]);
        $lava->LineChart('slope', $dataTableSlope, [
            'title' => 'lejtés',
            'legend' => ['position' => 'none'],
        ]);
        $blc->chart('LineChart', 'slope', $lava);
        $blc->pre('
// Line chart:
$dataTableSlope->addNumberColumn(\'x\')
            ->addNumberColumn(\'y\')
            ->addRow([0, 0])
            ->addRow([100, $f3->_slope]);
        $lava->LineChart(\'slope\', $dataTableSlope, [
            \'title\' => \'lejtés\',
            \'legend\' => [\'position\' => \'none\'],
        ]);
        $blc->chart(\'LineChart\', \'slope\', $lava);     
        ');

        $dataTable1 = $lava->DataTable();
        $dataTable1->addNumberColumn('x');
        $dataTable1->addNumberColumn('y');
        $dataTable1->addRow([1, 5]);
        $dataTable1->addRow([2, 20]);

        $dataTable2 = $lava->DataTable();
        $dataTable2->addNumberColumn('x');
        $dataTable2->addNumberColumn('y');
        $dataTable2->addRow([3, 35]);

        $tables = new \Khill\Lavacharts\DataTables\JoinedDataTable($dataTable1,$dataTable2);

        $lava->ScatterChart('3', $tables, ['legend' => ['position' => 'none'],'title' => 'Multiple dataTable scatter plot test',]);
        $blc->chart('ScatterChart', '3', $lava);

        $blc->pre('
// Scatter from two datasets        
$dataTable1 = $lava->DataTable();
$dataTable1->addNumberColumn(\'x\');
$dataTable1->addNumberColumn(\'y\');
$dataTable1->addRow([1, 5]);
$dataTable1->addRow([2, 20]);

$dataTable2 = $lava->DataTable();
$dataTable2->addNumberColumn(\'x\');
$dataTable2->addNumberColumn(\'y\');
$dataTable2->addRow([3, 35]);

$tables = new \Khill\Lavacharts\DataTables\JoinedDataTable($dataTable1,$dataTable2);

$lava->ScatterChart(\'3\', $tables, [\'legend\' => [\'position\' => \'none\'],\'title\' => \'Multiple dataTable scatter plot test\',]);
$blc->chart(\'ScatterChart\', \'3\', $lava);        
        ');

        $blc->h2('Bolt database');
        $blc->pre(json_encode($ec->readData('bolt'), JSON_PRETTY_PRINT));

        $blc->h2('Material database');
        $blc->pre(json_encode($ec->readData('mat'), JSON_PRETTY_PRINT));

        $blc->h1('Tests');

        $blc->input('x0', 'no validation: abc', 'abc', '', '', false);
        $blc->txt('in Hive: '.$f3->_x0);

        $blc->input('x1', 'numeric: abc', 'abc', '', '', 'numeric');
        $blc->txt('in Hive: '.$f3->_x1);

        $blc->input('x2', 'numeric: -10', -10, '', '', 'numeric');
        $blc->txt('in Hive: '.$f3->_x2);

        $blc->input('x3', 'numeric: 113.25', 113.25, '', '', 'numeric');
        $blc->txt('in Hive: '.$f3->_x3);

        $blc->input('4', 'alphanumeric: abc', 'abc', '', '', 'alpha_numeric');
        $blc->txt('in Hive: '.$f3->_x4);

        $blc->input('x5', 'alphanumeric: abc d', 'abc d', '', '', 'alpha_numeric');
        $blc->txt('in Hive: '.$f3->_x5);

        $blc->input('x6', 'alphanumeric: $', '$', '', '', 'alpha_numeric');
        $blc->txt('in Hive: '.$f3->_x6);
    }
}
