<?php

namespace Calculation;

Class Readme extends \Ecc
{

    public function calc($f3)
    {
        $blc = \Blc::instance();
        $ec = \Ec::instance();

        $text1 = file_get_contents($f3->BASE.'vendor/resist/ecc-calculations/README.md');
        $blc->md($text1);

        $blc->hr();
        $blc->h1('Annex', 'Autogenerated lists and examples');

        $blc->txt('Bolt database:');
        $blc->pre(json_encode($ec->data('bolt'), JSON_PRETTY_PRINT));

        $blc->txt('Material database:');
        $blc->pre(json_encode($ec->data('mat'), JSON_PRETTY_PRINT));
    }
}
